MIN_INST=15
HOURS_PER_DAY = 24
DEFAULT_DAYS = 30
DEFAULT_BACKTEST_MONTHS = 6
DEFAULT_PRICE_COLUMN = "price"
DEFAULT_TIMESTAMP_COLUMN = "timestamp"
DEFAULT_DATA_FILE = "data/synthetic_prices_5m.csv"
CALIBRATE_ARIMA = False
trading_cost = .0
#DEFAULT_EVALUATION_MODE = "pnl"   
#DEFAULT_EVALUATION_MODE = "battery_mse"
DEFAULT_EVALUATION_MODE = "battery"

ARIMA_C = 0.0006963697009544961
ARIMA_PHI = [0.34474089400776264]
ARIMA_THETA = []
ARIMA_P = 1
ARIMA_D = 1
ARIMA_Q = 0

RANDOM_FOREST_N_ESTIMATORS = 50
RANDOM_FOREST_MIN_TRAINING_ROWS = 24 * 30
RANDOM_FOREST_REFIT_INTERVAL = 24
RANDOM_FOREST_RANDOM_STATE = 42
RANDOM_FOREST_MAX_DEPTH = 5